using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

namespace Reimnop.MvvmHelper.Generator;

[Generator]
public sealed class ViewRegistryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // find all class declarations with the attribute
        var classesProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Reimnop.MvvmHelper.ViewModelViewAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetClassInfo(ctx))
            .Where(static m => m is not null)
            .Collect();
        var compilationProvider = context.CompilationProvider;
        var combinedProvider = compilationProvider.Combine(classesProvider);

        // register source output
        context.RegisterSourceOutput(combinedProvider, static (spc, tuple) =>
        {
            var (compilation, classes) = tuple;
            
            // skip generating for assemblies with no decorated classes
            if (classes.IsDefaultOrEmpty)
                return;
            
            var registryNamespace = $"{compilation.AssemblyName}.Generated";
            spc.AddSource("ViewRegistry.g.cs", GeneratedRegistrySource(registryNamespace, classes));
            spc.AddSource("ViewRegistryRegistration.g.cs", GeneratedRegistryRegistrationSource(registryNamespace, classes));
        });
    }

    private static string GeneratedRegistryRegistrationSource(string registryNamespace, ImmutableArray<ClassInfo?> classes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {registryNamespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated helper for registering the generated view registry.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class ViewRegistryRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds all <see cref=\"Reimnop.MvvmHelper.ViewModelViewAttribute\" />-decorated ViewModels");
        sb.AppendLine("    /// in the current assembly to the provided service collection");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddViewModels(this IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var classInfo in classes.OfType<ClassInfo>())        
        {
            sb.AppendLine($"        services.AddTransient<global::{classInfo.ViewModelFullName}>();");
        }
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds the view registry to the provided service collection.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddViewRegistry(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.AddSingleton<global::Reimnop.MvvmHelper.IViewRegistry, global::{registryNamespace}.ViewRegistry>();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds the view registry, view models and view locator to the provided service collection.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddMvvm(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        services.AddViewModels();");
        sb.AppendLine("        services.AddViewRegistry();");
        sb.AppendLine("        services.AddSingleton<global::Reimnop.MvvmHelper.IViewLocator, global::Reimnop.MvvmHelper.ViewLocator>();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GeneratedRegistrySource(string registryNamespace, ImmutableArray<ClassInfo?> classes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {registryNamespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated view registry.");
        sb.AppendLine("/// Maps ViewModel types to factory functions that");
        sb.AppendLine("/// create the corresponding Views. Generated from classes decorated with");
        sb.AppendLine("/// <see cref=\"Reimnop.MvvmHelper.ViewModelViewAttribute\" />.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal class ViewRegistry : global::Reimnop.MvvmHelper.AbstractGeneratedViewRegistry");
        sb.AppendLine("{");

        // factory function fields
        foreach (var classInfo in classes.OfType<ClassInfo>())
        {
            sb.AppendLine($"    private static readonly Func<global::Avalonia.Controls.Control> {classInfo.ViewModelFullName.Replace('.', '_')}_Factory = () => new global::{classInfo.ViewFullName}();");
        }

        sb.AppendLine();

        // view model type -> factory map
        sb.AppendLine("    protected override Dictionary<Type, Func<global::Avalonia.Controls.Control>> ViewFactories { get; } = new()");
        sb.AppendLine("    {");
        foreach (var classInfo in classes.OfType<ClassInfo>())
        {
            sb.AppendLine($"        {{typeof(global::{classInfo.ViewModelFullName}), {classInfo.ViewModelFullName.Replace('.', '_')}_Factory}},");
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");
        
        return sb.ToString();
    }

    private static ClassInfo? GetClassInfo(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
            return null;
        
        var viewModelFullName = symbol.ToDisplayString();
        
        var attributes = symbol.GetAttributes();
        var viewModelViewAttribute = attributes
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "Reimnop.MvvmHelper.ViewModelViewAttribute");

        if (viewModelViewAttribute is null)
            return null;

        var typeofArgument = viewModelViewAttribute.ConstructorArguments.FirstOrDefault();
        if (typeofArgument.Value is not INamedTypeSymbol viewTypeSymbol)
            return null;
        
        var viewFullName = viewTypeSymbol.ToDisplayString();

        return new ClassInfo(viewModelFullName, viewFullName);
    }

    private record ClassInfo(string ViewModelFullName, string ViewFullName);
}